vending/urls.py
from django.contrib import admin  
from django.urls import path  
from Storage import views  
urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('vendi', views.vendi),
    path('show',views.show)
]

Storage/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
	pid = models.IntegerField()
	name = models.CharField(max_length=200)
	price = models.IntegerField()
	description = models.CharField(max_length=200)


class Machine(models.Model):
	Mid = models.CharField(max_length=100)
	location = models.CharField(max_length=200)
	active_template = models.CharField(max_length=200)


class Payments(models.Model):
	transactionid = models.CharField(max_length=1000)
	product = models.ManyToManyField(Product)


class Users(models.Model):
	Name = models.CharField(max_length=100)
	designation = models.CharField(max_length=100)
	Inprod = models.ManyToManyField(Product, related_name="Inprod")
	OutProd = models.ManyToManyField(Product, related_name="Outprod")

home/models.py
from django.db import models

# Create your models here.

Storage/forms.py
from django import forms  
from Storage.models import Product  


class ProductForm(forms.ModelForm):
    class Meta:  
        model = Product  
        fields = "__all__"

Storage/views.py
from django.shortcuts import render, redirect  
from Storage.forms import ProductForm
from Storage.models import Product
# Create your views here.  
def vendi(request):
    if request.method == "POST":  
        form = ProductForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = ProductForm()  
    return render(request,'index.html',{'form':form})  
def edit(request, id):
    product = Product.objects.filter(pid=id)
    #Product = Product.objects.get()
    return render(request,'edit.html', {'Product':product})
def show(request):
    Products = Product.objects.all()
    for p in Products:
        print(p.name)
    return render(request,"show.html",{'Products':Products})
def update(request, id):
    product = Product.objects.get(pid=id)
    form = ProductForm(request.POST, instance = product)
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'Product': product})
def destroy(request, id):  
    product = Product.objects.get(id=id)
    product.delete()
    return redirect("/show")

home/views.py
from django.shortcuts import render

# Create your views here.

Storage/templates/Edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/update/{{product.pid}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Product Id:</label>
    <div class="col-sm-4">
        <input type="text" name="pid" id="id_pid" required maxlength="20" value="{{ product.pid }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Product Name:</label>
    <div class="col-sm-4">
        <input type="text" name="name" id="id_pname" required maxlength="100" value="{{ product.name }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Product Price:</label>
    <div class="col-sm-4">
        <input type="number" name="price" id="id_price" required maxlength="254" value="{{ product.price }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Description :</label>
    <div class="col-sm-4">
        <input type="text" name="description" id="id_description" required maxlength="254" value="{{ product.description }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

Storage/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/vendi">
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Product id:</label>
    <div class="col-sm-4">  
      {{ form.pid }}
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Product Name:</label>
    <div class="col-sm-4">  
      {{ form.name }}
    </div>  
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Description</label>
    <div class="col-sm-4">
      {{ form.description }}
    </div>
  </div>
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">price:</label>
    <div class="col-sm-4">  
      {{ form.price }}
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

Storage/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product Records</title>
     {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Product ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Description</th>
    </tr>
    </thead>
    <tbody>
{% for product in Products %}
    <tr>
        <td>{{ product.pid }}</td>
        <td>{{ product.name }}</td>
        <td>{{ product.price }}</td>
        <td>{{ product.description }}</td>
        <td>
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="/delete/{{ employee.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/vendi" class="btn btn-primary">Add New Record</a></center>
</body>
</html>